project: folio-jenkins-agent
configVersion: 1

cleanup:
  disable: true
---
image: folio-jenkins-agent
dockerfile: Dockerfile
context: .

args:
  TERRAFORM_VERSION: '{{ env "TERRAFORM_VERSION" "1.6.6" }}'
  HELM_VERSION: '{{ env "HELM_VERSION" "3.15.4" }}'
  KUBECTL_VERSION: '{{ env "KUBECTL_VERSION" "1.28.0" }}'
  KAFKA_VERSION: '{{ env "KAFKA_VERSION" "3.8.0" }}'
